baseurl = "https://www.xueyuyao.com/"
languageCode = "en-us"
title = "薛玉瑶的博客"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"
theme = "vienna"
[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    github = "yuyaoxue"
    googleplus = "yuyaoxue0617"
    # Disqus shortname
    disqus = "Your disqus shortname"
    # Google Analytics API key.
    ga_api_key = "Your Google Analytics tracking id"
    # Mixpanel API key.
    mixpanel_api_key = "Your Mixpanel API key"
    author = "xueyuyao"
    avatar = "/path/to/avatar"
    contact = "Your contact link (ex. mailto:foo@example.com)"
    bio = "Your short bio"
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "每天都是一种练习"
    themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.
[permalinks]
post = "/:year/:month/:day/:filename/"
